---
title: "Data download from Yahoo"
output:
  html_document: default
  pdf_document: default
date: "2025-06-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("PerformanceAnalytics")
```


```{r echo=TRUE}
library(quantmod) # needed to download the data
library(PerformanceAnalytics) # used to compute returns
```

```{r echo=TRUE}
# Get monthly data from Yahoo for Apple and Johnson and Johnson amd SP500
symbol.vec <- c("AAPL", "JNJ", "^GSPC")
getSymbols(symbol.vec,from = "2020-01-01", to = "2024-12-31", periodicity ="monthly") 
```


 Next we get the returns for each asset using adjusted prices stored in the column with the name of the form assetsymbol.Adjusted  (for Apple (AAPL.Adjusted))

```{r echo=TRUE}
AAPL.Adj <- AAPL[, "AAPL.Adjusted"]
# Calculate monthly simple returns
AAPL.returns <- CalculateReturns(AAPL.Adj, method = "simple")
# Remove NA (first return will be NA)
AAPL.returns <- na.omit(AAPL.returns)
# Next we do the same with the data corresponding to JNJ
JNJ.Adj <- JNJ[, "JNJ.Adjusted"]
# Calculate monthly simple returns
JNJ.returns <- CalculateReturns(JNJ.Adj, method = "simple")
# Remove NA (first return will be NA)
JNJ.returns <- na.omit(JNJ.returns)
# Next we do the same with the data corresponding to SP500
SP500.Adj <- GSPC[, "GSPC.Adjusted"]
# Calculate monthly simple returns
SP500.returns <- CalculateReturns(SP500.Adj, method = "simple")
# Remove NA (first return will be NA)
SP500.returns <- na.omit(SP500.returns)
# To remove the dates and the column names use the following
AAPL<-coredata(AAPL.returns)
colnames(AAPL)<-NULL
JNJ<-coredata(JNJ.returns)
colnames(JNJ)<-NULL
SP500<-coredata(SP500.returns)
colnames(SP500)<-NULL
# Next we combine the data in the object called returns
returns<-cbind(AAPL,JNJ, SP500)
```

ext we compute the means, the covariance and the standard deviations

```{r echo=TRUE}
mean_vect <- colMeans(returns)
cov_mat <- cov(returns)
cov_mat
sd_vect <- sqrt(diag(cov_mat))
mean_vect
sd_vect
```

```{r}
library(quantmod)

symbols <- c("AAPL", "MSFT", "AMZN", "GOOGL", "META",
             "TSLA", "JNJ", "PG", "XOM", "JPM",
             "NVDA", "^GSPC")

getSymbols(symbols, 
           from = "2019-01-01", 
           to = "2024-12-31", 
           periodicity = "monthly")

```


```{r}
library(quantmod)
getSymbols("TB3MS", src = "FRED")

# Transfer the annual rate into monthly RFR
rf_annual <- TB3MS / 100
rf_monthly <- rf_annual / 12

head(rf_monthly)  # Check the first few months

```


# 2.2
